language: python
python: 3.7
sudo: false

env:
  global:
    - secure: "Yj0NnE/FYkVVWsa8gcJNwTn6ISVqluXjsM7XpVcVbab9qd4kwHj8dapd0CwMwGRoEqaPqF+7cWKPK+nu5qyinhaJDWWJA2jAIo9uFkPQ1zHL2D94nK2Z6yupA7xwmMNfyIFuVF1h/r+8UPz3J0Cn/n9i8DMW0RIhbQLT0Uzse6tWqW3fweat9ty6ZcxZDzBemKEQj3RVBw7E2PhqQOjJv7lV7H24pK1RhZJN9UHVI1EPF7cxy9enC6IYYPrIg/LEC0c2ScMRJBz1z7CMEFV3bRpzGjP2y2+xzL15LxciCWzl+Ww43FChTbHGHDl7pPJG+Aenz+kASmm0ShK8WcPbPsyh1/uzLXVXRlOD9TJBBg49c6uDAdVFD4+xBYcqyNfHvWOzixTZZ188JSJHGri11nuhPtWUnyfrUa2wpHaxyaaItIGZUG3q3IdN2tl/z+4iEkQsako6UMizU+tTEGlPoSc1qRL45j64ZJhjOZIF8K0DBiy2v3iSTuD5VODkTDhe3QX5d9z8t1ZrHYNIBJIilP7bci1Fm3JrXBZ+EyLx3K3f5BBtWEpSNlYsfjxwo4pfAlTKiCc9PO79Ip+K+C4QNS0Rfgf9tVqlEjgnkLhQjMWLf6+PRPAtGnQrXNHZuhTh6tChbt6Gww0NG/3VkuRoVeoG/omNDOghqBvSPq3/Q94="

matrix:
  include:
    - name: Project summary
      env: TWINCAT_SUMMARY=1
    - name: Pragma linting
      env: TWINCAT_PRAGMALINT=1
    - name: Documentation building
      env: TWINCAT_BUILD_DOCS=1

install:
  # Pull PCDS standard CI scripts 
  - git clone --depth 1 https://github.com/pcdshub/pcds-ci-helpers.git

script:
  # Execute pytmc summarizing, linting, and documentation building
  - source pcds-ci-helpers/travis/init.sh
