<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="Fast_Faults_Evaluate" Id="{667ad34f-81ff-0404-3362-bb63097d9547}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Fast_Faults_Evaluate
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[g_FastFaultOutput1.EvaluateOutput(i_xVeto:=PMPS_GVL.stCurrentBeamParameters.aStoppers[PMPS.L_Stopper.ST1]);]]></ST>
    </Implementation>
    <LineIds Name="Fast_Faults_Evaluate">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>