<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="FB_UndulatorSegment" Id="{986484f4-a7ca-4f8c-bada-b360e7740d21}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_UndulatorSegment
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	{attribute 'pytmc' := '
		pv: KDes
		link: KDes
	'}
	fbKDesired : FB_LREALFromEPICS;

	{attribute 'pytmc' := '
		pv: KAct
		link: KAct
	'}
	fbKActual : FB_LREALFromEPICS;

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbKDesired();
fbKActual();]]></ST>
    </Implementation>
    <LineIds Name="FB_UndulatorSegment">
      <LineId Id="3" Count="0" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>