IOC_TOP = /reg/g/pcds/epics/R7.0.2-2.0/ioc/ads-ioc/v0.0.2
IOC_INSTANCE_PATH := $(shell pwd)

PROJECT_NAME = Arbiter
PROJECT_PATH := ../../Arbiter/Arbiter.tsproj
PLC = ArbiterPLC

PYTMC_OPTS = 
PREFIX = PREFIX:

include $(IOC_TOP)/iocBoot/templates/Makefile.base
